site_name: BCA Notes
site_description: Notes for my college course.
site_author: myxi
docs_dir: notes/
repo_name: "eeriemyxi/bca-notes"
repo_url: "https://github.com/eeriemyxi/bca-notes"
nav:
  - Home: index.md
  - 1st Semester:
    - "AEC: Alternative English":
      - Syllabus: sem1/aec-eng/syllabus.md
      - "Sujata Bhatt: So Many Oaks": sem1/aec-eng/so-many-oaks.md
      - "Sarojini Naidu: The Palanquin Bearers": sem1/aec-eng/the-palanquin-bearers.md
      - "W. B. Yeats: No Second Troy": sem1/aec-eng/no-second-troy.md
      - "Margaret Atwood: This is a Photograph of Me": sem1/aec-eng/photograph-of-me.md
      - "Mahim Bora: Audition": sem1/aec-eng/audition.md
      - "Bryan MacMahon: The Ring": sem1/aec-eng/the-ring.md
    - Mathematics:
      - Syllabus: sem1/math/syllabus.md
      - Unit 1:
        - Sets: sem1/math/u1/sets.md
        - Relations: sem1/math/u1/relations.md
        - Functions: sem1/math/u1/functions.md
      - Unit 2:
        - Definition and Types: sem1/math/u2/first.md
        - Operations: sem1/math/u2/second.md
        - Identities and Inverses: sem1/math/u2/three.md
        - Applications and Properties: sem1/math/u2/four.md
      - Previous Year Papers:
        - 2024: sem1/math/pyq/2024.md
    - Computer Fundamentals:
      - Syllabus: sem1/fundamentals/syllabus.md
      - Unit 1: sem1/fundamentals/unit-1.md
    - Introduction to C:
      - Syllabus: sem1/c/syllabus.md
      - Unit 1:
        - C Fundamentals and Program Structure: sem1/c/u1-i.md
        - Data, Variables, and Constants in C: sem1/c/u1-ii.md
        - Operators, Expressions, and I/O: sem1/c/u1-iii.md
      - Unit 2: sem1/c/u2.md
      - Unit 3: sem1/c/u3.md
      - Unit 4: sem1/c/u4.md

theme:
    name: material
    palette: gruvbox_dark
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate
theme:
    name: material
    palette:
        - scheme: slate
          primary: deep purple
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        - scheme: default
          primary: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate

plugins:
  - search
  - mermaid2
  
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          toc_depth: 1-4
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  # - js/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/copy-tex.min.js

extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/copy-tex.css

